### ISSUE TITLE
SSEC

### ISSUE THREAD

**Issue by CiroBoxHub** [coyotevz/anviz-a300#1]
Mi sareste di grandissimo aiuto. Vorrei sapere gentilmente perchè il valore di SSEC https://github.com/coyotevz/anviz-a300/blob/master/anviz.py#L21 è impostato con quella data e perchè al 2-1-2000 e non al 1-1-2000

Grazie mille!

**Comment by coyotevz** [comment]
@CiroBoxHub, I do not know the reason exactly, but [here's](https://github.com/Monits/Anviz-Protocol/blob/master/src/main/java/com/monits/anviz/TimeKeeper.java#L154) a good reason. This works well for me. Sorry, I can not write Italian.

**Comment by CiroBoxHub** [comment]
No problem! I'm sorry for writing in Italian. thank you so much
