### ISSUE TITLE
integration issue

### ISSUE THREAD

**Issue by yashgupta045** [coyotevz/anviz-a300#5]
Hi, Can i connect with you via skype...because i wanna discuss about briefly regarding this API..

**Comment by coyotevz** [comment]
Hi, I can't speak English fluently, you can contact me by mail if you prefer. Anyway we can talk about it here. Regards!

**Comment by yashgupta045** [comment]
i want to know how this API will work and how the device connects with the application

**Comment by yashgupta045** [comment]
i want to develop this in PHP

**Comment by coyotevz** [comment]
Hello, you can see the following example [coyotevz/anviz-sync](https://github.com/coyotevz/anviz-sync) to see how the API works, the connection with the device is made using the socket library, this software works with devices that are no longer sold, the firmware version must be 01.74.A2 or less.

You can see [CommsProtocol](https://github.com/benperiton/anviz-protocol/raw/master/Docs/CommsProtocol.pdf) for more information.

Regards!
